schema_version: 1

context:
  name: tabpfn-extensions
  version: 0.4.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tabpfn_extensions-${{ version }}.tar.gz
  sha256: 64e30b097a29d430f970616302a25f7f1d40add2638e3c191432b8e992179a92

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=2.2.2
    - pytorch >=2.1
    - scikit-learn >=1.6.0
    - scipy >=1.11.1
    - tabpfn >=7.0.0
    - tabpfn-common-utils >=0.2.13
tests:
  - script:
      interpreter: python
      content: |
        import os
        # Importing tabpfn fails when 'CI' environment variable is set to anything other than 'true' or 'false' (e.g., 'azure').
        # Ref.: https://github.com/PriorLabs/TabPFN/issues/482
        os.environ["CI"] = "true"
        import tabpfn_extensions
  - script:
      - pip check
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip

about:
  summary: 'TabPFN: Foundation model for tabular data'
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://priorlabs.ai
  repository: https://github.com/PriorLabs/tabpfn-extensions

extra:
  recipe-maintainers:
    - janjagusch
