schema_version: 1

context:
  name: tabpfn-extensions
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tabpfn_extensions-${{ version }}.tar.gz
  sha256: 8049769fffc8d5e8d03c4920ad506333665b6960cab1d4023dfff50492959d80

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.4.0,<3
    - pytorch >=2.1,<3
    - scikit-learn >=1.2.0,<1.7
    - scipy >=1.11.1,<2
    - tabpfn >=2.1.1,<7
    - tabpfn-common-utils >=0.2.0
tests:
  - script:
      interpreter: python
      content: |
        import os
        # Importing tabpfn fails when 'CI' environment variable is set to anything other than 'true' or 'false' (e.g., 'azure').
        # Ref.: https://github.com/PriorLabs/TabPFN/issues/482
        os.environ["CI"] = "true"
        import tabpfn_extensions
  - script:
      - pip check
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip

about:
  summary: 'TabPFN: Foundation model for tabular data'
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://priorlabs.ai
  repository: https://github.com/PriorLabs/tabpfn-extensions

extra:
  recipe-maintainers:
    - janjagusch
